apiVersion: apps/v1
kind: Deployment
metadata:
  name: dungeons-and-dragons
  labels:
    app: dungeons-and-dragons
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dungeons-and-dragons
  template:
    metadata:
      labels:
        app: dungeons-and-dragons
    spec:
      containers:
        - name: dungeons-and-dragons
          image: galya777/dungeons-and-dragons:latest
          ports:
            - containerPort: 8080
