---
all:
  children:
    web:
      hosts:
        web1:
          ansible_host: 192.168.1.100
          ansible_user: ubuntu
          ansible_password: mypassword
        web2:
          ansible_host: 192.168.1.101
          ansible_user: ubuntu
          ansible_password: mypassword
    db:
      hosts:
        db1:
          ansible_host: 192.168.1.102
          ansible_user: ubuntu
          ansible_password: mypassword