apiVersion: v1
kind: Service
metadata:
  name: dungeons-and-dragons-service
spec:
  selector:
    app: dungeons-and-dragons
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080 # Optional: Specify a NodePort (must be between 30000-32767)
  type: NodePort
