stages:
  - build
  - test
  - deploy

jobs:
      build:
        stage: build
        script:
          - mvn clean package
      test:
        stage: test
        script:
          - mvn test
      deploy:
        stage: deploy
        script:
          - mvn deploy

triggers:
  - push
  - pull_request